### ISSUE TITLE
Cannot pass "type" query param to get_logs.

### ISSUE THREAD

**Issue by JamesPoel** [ground-creative/tuyapiphp#1]
Hi,

I'm trying to get the logs for a particular device, but the example given:

$tuya->devices($token)->get_logs($deviceId)

Causes error: 

(
    [code] => 1102
    [msg] => type param is null
    [success] => 
    [t] => 1638617686644
)

This is because the "type" query param is required for get_status, see here:

https://developer.tuya.com/en/docs/cloud/0a30fc557f?id=Ka7kjybdo0jse

I have tried:

$tuya->devices($token)->get_logs($deviceId, ['type' => '1,2,3,4,5,6,7,8,9']),

But it causes the URL to become malformed (i.e. it's missing the "/v1.0/devices/{device_id}/logs" part)

GET https://openapi.tuyaeu.com?type=1%2C2%2C3%2C4%2C5%2C6%2C7%2C8%2C9

It looks as though the package does not correctly handle payloads for GET requests.

**Comment by ifsale** [comment]
I am trying to solve the issue, but as I correct the get values in the url the signature brakes.

I'll update the code soon as I have a proper solution.

**Comment by sarathx4** [comment]
> I am trying to solve the issue, but as I correct the get values in the url the signature brakes.
> 
> I'll update the code soon as I have a proper solution.

Hi, any solutions for sending params via GET? I'm trying to get device logs too.

**Comment by grivachenko** [comment]
>>Sort the keys according to the dictionary
"end_time, start_time, type" or ksort($payload);

**Comment by ground-creative** [comment]
ksort($payload);

That actually solved the issue.

Well spotted....
