### ISSUE TITLE
Getting Only Switch_1 State

### ISSUE THREAD

**Issue by huseyinergen** [ground-creative/tuyapiphp#10]
Hello everyone.
How to get only the switch_1 state with code? I want to make a PHP page with an icon. Green-led and red-led icon. When status is 1(open or true) green icon if the other state icon will appear red.

`<?php
error_reporting(E_ALL);
ini_set('display_errors', '1');
    $config =
    [
        "secretKey" => "xxxx" ,
        "accessKey" => "xxxx" ,
        'baseUrl' => 'https://openapi.tuyaeu.com' ,
    ];
    require( 'TuyaApi.php' );
    $device_id = 'xxxx';
  $tuya = new \tuyapiphp\TuyaApi( $config );
  $token = $tuya->token->get_new( )->result->access_token;

// Get device status
$sonuc = $tuya->devices( $token )->get_status($device_id);
echo "<pre>";
//$object = (object) $sonuc;
var_dump($sonuc);
echo "</pre>";
echo "<br>";
 ?> `

**Comment by ground-creative** [comment]
According to the manual here:
https://developer.tuya.com/en/docs/cloud/f76865b055?id=Kag2ycn1lvwpt

The return values for the get status would be something like this:

"result": [
        {
            "code": "switch_led",
            "value": true
        },
        {
            "code": "work_mode",
            "value": "scene_2"
        }]

So to get the switch_led value for instance u would do something like this:

foreach ($sonuc['result'] as $k=>$v)
{
      if ($v['code'] == "switch_led")
     {
                $switch_led_value = $v['value'];
      }
}

That should work hopefully.

**Comment by huseyinergen** [comment]
Thank you so much for your response. But I got an error when i tried your code.

`Fatal error: Uncaught Error: Cannot use object of type stdClass as array in /volume1/web/tuya/sadece/get.php:26
Stack trace:
#0 {main}
  thrown in /volume1/web/tuya/sadece/get.php on line 26`

**Comment by ground-creative** [comment]
Cast it to an array

$sonuc = (array)$sonuc;

**Comment by huseyinergen** [comment]
Nothing changed :(

**Comment by ground-creative** [comment]
what is on line 21 ?

**Comment by ground-creative** [comment]
U need to cast it an array before that line:

$arr = (array)$sonuc;

foreach ($arr['result'] as $k=>$v)

**Comment by huseyinergen** [comment]
Fatal error: Uncaught Error: Cannot use object of type stdClass as array in /volume1/web/tuya/sadece/get.php:25 Stack trace: #0 {main} thrown in /volume1/web/tuya/sadece/get.php on line 25

line25: 
if ($v['code'] == "switch_led")

**Comment by ground-creative** [comment]
again before line 25:

$v = (array)$v;

**Comment by huseyinergen** [comment]
there is no an error with below codes but how i get switchledvalue? 
echo $switch_led_value; do not work..

`$arr = (array)$sonuc;

foreach ($arr['result'] as $k=>$v)
$v = (array)$v;
{
if ($v['code'] == 'switch_led')
{
$switch_led_value = (array)$v['value'];
}
}`

**Comment by huseyinergen** [comment]
var_dump($sonuc);
like older code. Listing every value...

tried with;
var_dump($switch_led_value);
----------
Notice: Undefined variable: switch_led_value in /volume1/web/tuya/sadece/get.php on line 30 NULL
-------
var_dump(switch_1 );
Warning: Use of undefined constant switch_1 - assumed 'switch_1' (this will throw an Error in a future version of PHP) in /volume1/web/tuya/sadece/get.php on line 30 string(8) "switch_1"



No one giving me switch_led value... :(

**Comment by huseyinergen** [comment]
var_dump($switch_1_value );
and getting result;
array(1) { [0]=> bool(false) }

**Comment by ground-creative** [comment]
error_reporting(E_ALL);
ini_set('display_errors', '1');
$config =
[
"secretKey" => "xxxx" ,
"accessKey" => "xxxx" ,
'baseUrl' => 'https://openapi.tuyaeu.com' ,
];
require( 'TuyaApi.php' );
$device_id = 'xxxx';
$tuya = new \tuyapiphp\TuyaApi( $config );
$token = $tuya->token->get_new( )->result->access_token;

// Get device status
$sonuc = $tuya->devices( $token )->get_status($device_id);

foreach ($sonuc['result'] as $k=>$v)
{
if ($v['code'] == "switch_1")
{
$switch_1 = $v['value'];
echo $switch_1;
break;
}
echo " key not found"
}

**Comment by huseyinergen** [comment]
`foreach ($arr["result"] as $k=>$v)
$v = (array)$v;
{
if ($v["code"] == "switch_1")
{
$switch_1_value = (array)$v["value"];

}
}
//var_dump($switch_1_value );
var_dump($switch_1_value );`


when tried this code result is;
array(1) { [0]=> bool(false) }


Now finally; how to got this variable?

**Comment by huseyinergen** [comment]
echo ($switch_1_value[0] );
GREAT. MANY MANY THANKS... THANK YOU SO MUCH....
