### ISSUE TITLE
Where I can get App ID?

### ISSUE THREAD

**Issue by shamimbdpro** [ground-creative/tuyapiphp#3]
![image](https://user-images.githubusercontent.com/39990205/152147667-e146e2a3-285d-4477-a82d-54936e0ac6bd.png)

**Comment by ground-creative** [comment]
HI,

Please follow this setup instructions:
https://github.com/codetheweb/tuyapi/blob/master/docs/SETUP.md

Afterwords u should be able to follow the guidelines from tuya to see your app id.
