### ISSUE TITLE
Error "ip don't have access to this API" But Tuya API Explore is working

### ISSUE THREAD

**Issue by sanjulanipun** [ground-creative/tuyapiphp#6]
after config all data this error coming.
![image](https://user-images.githubusercontent.com/32708235/188540963-35771d1b-94f3-497b-a9e0-0e2345d29a78.png)
![image](https://user-images.githubusercontent.com/32708235/188541432-c7dc4ca3-61e0-4a12-a7a1-b91cdb69c368.png)

i add my ip address into cloud. but still same error.
![image](https://user-images.githubusercontent.com/32708235/188541160-7797df86-a628-4ef9-919b-5aa7469baf4a.png)

but in tuya api explore is working.
![image](https://user-images.githubusercontent.com/32708235/188541860-fab9ecca-a313-4ad6-a80e-5a7f5b60c67b.png)

**Comment by StanekO** [comment]
Hi, try this:
China Data Center	https://openapi.tuyacn.com
Western America Data Center	https://openapi.tuyaus.com
Eastern America Data Center	https://openapi-ueaz.tuyaus.com
Central Europe Data Center	https://openapi.tuyaeu.com
Western Europe Data Center	https://openapi-weaz.tuyaeu.com
India Data Center	https://openapi.tuyain.com
