### ISSUE TITLE
get_logs method not working to display device logs.

### ISSUE THREAD

**Issue by shamimbdpro** [ground-creative/tuyapiphp#8]
can you help me to figure out why get_logs method not working. saying sign invalid. but other method working fine.

![image](https://github.com/ground-creative/tuyapiphp/assets/39990205/d4cafab2-7d82-4be4-b7e9-49d553e47ce9)

{
    "success": true,
    "data": {
        "code": 1004,
        "msg": "sign invalid",
        "success": false,
        "t": 1683633313499,
        "tid": "5b551f21ee6011ed86f16a7eaa158d6d"
    },
    "message": "Data fetch successfully"
}

**Comment by shamimbdpro** [comment]
Tuya docs. 
https://developer.tuya.com/en/docs/cloud/device-management?id=K9g6rfntdz78a

**Comment by ground-creative** [comment]
Hi,

It looks to me that u are sending an array as type, but it should be a string as stated in the tuya api manual
https://developer.tuya.com/en/docs/cloud/device-management?id=K9g6rfntdz78a#title-37-API%20endpoint

U can look here for an example call
https://github.com/ground-creative/tuyapiphp/blob/master/tests/tuyapiphp/RequestTest.php

Just find this line
public function testGetCallWithParams()

**Comment by shamimbdpro** [comment]
Thank you, its work for one value but according to the tuya docs it suppose to accept multiple value by comma separate. 
![image](https://github.com/ground-creative/tuyapiphp/assets/39990205/c6e196a0-3ead-4c0b-9cf0-46829ac5ee7b)

is it possible to put multiple value to get all type of event together?

**Comment by ground-creative** [comment]
Added support to send multiple values separated by commas.
