### ISSUE TITLE
curl request error

### ISSUE THREAD

**Issue by sprotid** [ground-creative/tuyapiphp#9]
Had php8.1 windows http2 curl issue
1. no curl_error handling (even debugmode)
2. fix: curl_setopt($ch, CURLOPT_HTTP_VERSION, CURL_HTTP_VERSION_1_1);

**Comment by ground-creative** [comment]
I added this stuff in a new release.
Thanks for the feedback.

**Comment by ground-creative** [comment]
I added this stuff in a new release.
Thanks for the feedback.
